// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowsForms_Agenda_de_Activitati.Models;

namespace WindowsForms_Agenda_de_Activitati.Migrations
{
    [DbContext(typeof(EF_ApplicationContext))]
    partial class EF_ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("WindowsForms_Agenda_de_Activitati.Models.ActivitatiFamilie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Denumire")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalii")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioritate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataActivitate")
                        .HasColumnType("TEXT");

                    b.Property<int>("tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ActivitatiFamilie");
                });

            modelBuilder.Entity("WindowsForms_Agenda_de_Activitati.Models.EvenimentFirma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Denumire")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalii")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioritate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataEveniment")
                        .HasColumnType("TEXT");

                    b.Property<int>("tip")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("evenimente");
                });

            modelBuilder.Entity("WindowsForms_Agenda_de_Activitati.Models.Persoane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActivitatiFamilieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("grad_rudenie")
                        .HasColumnType("TEXT");

                    b.Property<string>("nume")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivitatiFamilieId");

                    b.ToTable("Persoane");
                });

            modelBuilder.Entity("WindowsForms_Agenda_de_Activitati.Models.Persoane", b =>
                {
                    b.HasOne("WindowsForms_Agenda_de_Activitati.Models.ActivitatiFamilie", null)
                        .WithMany("persoane")
                        .HasForeignKey("ActivitatiFamilieId");
                });
#pragma warning restore 612, 618
        }
    }
}
